const el=id=>document.getElementById(id),canvas=el('game'),ctx=canvas.getContext('2d'),city=new CityRoute(),witch=new FlightRigV5('../flight-v5/assets/');
const run=new RunModel(BALANCE,17,false);let started=false,pressed=false,heldKeys=new Set(),heldPointers=new Set(),castle,auraImage,muted=true,audioCtx,accumulator=0,frameLast=0,fxEvents=[];let backgroundLoaded,backgroundReady=false,backgroundBusy=false,assetWaiting=false;
const frame=el('frame');for(const event of ['contextmenu','selectstart','dragstart'])frame.addEventListener(event,e=>e.preventDefault());
canvas.addEventListener('touchstart',e=>e.preventDefault(),{passive:false});canvas.addEventListener('touchmove',e=>e.preventDefault(),{passive:false});
const pauseIcon='<svg viewBox="0 0 24 24" width="24" height="24" fill="currentColor"><rect x="5" y="4" width="5" height="16" rx="1"/><rect x="14" y="4" width="5" height="16" rx="1"/></svg>';
const soundIcon=off=>`<svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 9h4l5-4v14l-5-4H3z"/>${off?'<path d="m16 9 5 6m0-6-5 6"/>':'<path d="M16 8q5 4 0 8m3-11q8 7 0 14"/>'}</svg>`;
el('pause').innerHTML=pauseIcon;el('sound').innerHTML=soundIcon(true);
function tone(freq){if(muted)return;try{audioCtx??=new AudioContext();audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.045,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.16);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.17);}catch{}}
function clearInput(){pressed=false;heldKeys.clear();heldPointers.clear();}
function setPaused(value){if(!started||!['playing','finale'].includes(run.mode))return;paused=value;clearInput();accumulator=0;el('pauseMenu').hidden=!value;}
function start(){if(!ready)return;el('frame').dataset.screen='game';el('tutorial').hidden=true;el('heroCopy').hidden=false;const seed=el('repeatSeed').checked?(Number(el('seed').value)||17):1+crypto.getRandomValues(new Uint32Array(1))[0]%999999;el('seed').value=seed;run.reset(seed,el('potionMode').value==='freeze');assetWaiting=false;el('assetWait').hidden=true;GamePerf.reset();el('perfBadge').style.visibility='visible';el('perfBadge').hidden=!el('showFps').checked;started=true;paused=false;document.activeElement?.blur();clearInput();fxEvents=[];accumulator=0;previousVisual=null;witch.trail=[];witch.sparks=[];witch.tilt=0;witch.kickAge=100;el('menu').hidden=true;el('pauseMenu').hidden=true;document.querySelector('.result').hidden=true;el('potionMode').disabled=true;el('seed').disabled=true;draw();}
el('start').onclick=start;el('pause').onclick=()=>setPaused(!paused);el('resume').onclick=()=>setPaused(false);el('restartPaused').onclick=start;
el('sound').onclick=()=>{muted=!muted;el('sound').innerHTML=soundIcon(muted);el('sound').setAttribute('aria-pressed',String(!muted));el('sound').setAttribute('aria-label',muted?'Включить звук':'Выключить звук');tone(640);};
canvas.onpointerdown=e=>{if(!started||paused||assetWaiting||run.mode!=='playing')return;e.preventDefault();canvas.setPointerCapture(e.pointerId);heldPointers.add(e.pointerId);pressed=true;};
function releasePointer(e){heldPointers.delete(e.pointerId);pressed=heldPointers.size>0||heldKeys.size>0;}
canvas.onpointerup=canvas.onpointercancel=canvas.onlostpointercapture=releasePointer;
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName))return;if(e.code==='Escape'||e.code==='KeyP'){if(!e.repeat)setPaused(!paused);return;}if(['Space','ArrowUp','KeyW'].includes(e.code)){e.preventDefault();if(started&&!paused&&!assetWaiting&&run.mode==='playing'){heldKeys.add(e.code);pressed=true;}}});
window.addEventListener('keyup',e=>{heldKeys.delete(e.code);pressed=heldKeys.size>0||heldPointers.size>0;});window.addEventListener('blur',()=>setPaused(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)setPaused(true);});
const clamp=n=>Math.max(0,Math.min(1,n)),smooth=n=>{n=clamp(n);return n*n*(3-2*n);};
function castlePose(){const auto=run.mode==='finale'||run.mode==='victory'?run.finale:0,t=run.progress-82,scroll=t<8?t*94:752+94*(Math.min(auto,1.4)-Math.min(auto,1.4)**2/2.8),cx=-81+817.8-scroll,cy=185,cw=520,ch=520,doorX=cx+cw*.51,doorY=cy+ch*.82,approach=smooth(auto/2.4),enter=smooth((auto-2.2)/1.8);return {cx,cy,cw,ch,scroll,auto,enter,x:165+(doorX-165)*approach+enter*(cw*.14+70),y:(run.finalY??run.y)+(doorY-(run.finalY??run.y))*approach,height:70*(1-enter*.45)};}
const auraLayer=document.createElement('canvas');auraLayer.width=auraLayer.height=512;const auraColors=[];function prepareAura(){for(let hue=-24;hue<=24;hue+=6){const c=document.createElement('canvas');c.width=c.height=512;const g=c.getContext('2d');g.filter=`hue-rotate(${hue}deg)`;g.drawImage(auraImage,0,0,auraImage.width/2,auraImage.height/2,0,0,512,512);auraColors.push(c);}}
function drawAura(){if(run.shield<=0||run.mode!=='playing')return;const left=run.shield,warn=Math.max(0,1-left/2),layer=auraLayer.getContext('2d');layer.clearRect(0,0,512,512);layer.globalCompositeOperation='source-over';const tint=(Math.sin(run.elapsed*.45)*24+24)/6,lo=Math.floor(tint),blend=tint-lo;layer.globalAlpha=1;if(blend>0&&lo<8){layer.globalCompositeOperation='lighter';layer.globalAlpha=blend;layer.drawImage(auraColors[lo+1],0,0);layer.globalAlpha=1-blend;layer.drawImage(auraColors[lo],0,0);}else layer.drawImage(auraColors[lo],0,0);layer.globalAlpha=1;layer.globalCompositeOperation='source-atop';const beam=((run.elapsed*.38+(left<2?(2-left)**2*.32:0))%1)*880-184,g=layer.createLinearGradient(beam-76,0,beam+76,0);g.addColorStop(0,'#ffffff00');g.addColorStop(.5,'#f5e7ff99');g.addColorStop(1,'#ffffff00');layer.fillStyle=g;layer.fillRect(0,0,512,512);layer.globalCompositeOperation='source-over';ctx.save();ctx.globalAlpha=clamp(left/.35)*(.68+(.06+warn*.18)*Math.sin(run.elapsed*2.4+warn*warn*20));const p=witch.pose;ctx.translate(p.x+p.kickX,p.y+p.kickY);ctx.rotate(p.angle);ctx.translate(-21,-12);ctx.rotate(-5*Math.PI/180);ctx.scale(.84,.84);ctx.transform(1,0,.38,1,0,0);ctx.drawImage(auraLayer,-87,-101,175,190);ctx.restore();}
function drawWitch(){const age=run.hurtAge,recover=run.invulnerable>0&&run.mode==='playing';witch.kickAge=Infinity;if(recover){const k=witch.impactPose(Math.min(age,.24)),settle=age>1.8?(2.1-age)/.3:1;witch.pose.angle=witch.tilt-.22*settle;witch.pose.kickX=k.x*70/90*settle;witch.pose.kickY=k.y*70/90*settle;witch.hatSlip=k.hat*settle;}witch.drawTrail(ctx);ctx.save();if(recover&&age>=.3&&age<1.8)ctx.globalAlpha=(age-.3)%.5<.23?.15:1;witch.draw(ctx);ctx.restore();if(recover){witch.kickAge=.24+age%.6;witch.drawBats(ctx,false);witch.drawBats(ctx,true);}drawAura();}
function heart(x,y,on){ctx.save();ctx.translate(x,y);ctx.beginPath();ctx.moveTo(0,7);ctx.bezierCurveTo(-18,-4,-12,-17,0,-8);ctx.bezierCurveTo(12,-17,18,-4,0,7);ctx.fillStyle=on?'#f47c95':'#302539';ctx.fill();ctx.strokeStyle=on?'#ffc0bf':'#8e728e';ctx.lineWidth=1.3;ctx.stroke();ctx.restore();}
function hud(){ctx.save();ctx.shadowColor='#171122';ctx.shadowBlur=4;for(let j=0;j<3;j++)heart(25+j*26,28,j<run.lives);ctx.textAlign='center';ctx.font='bold 29px system-ui';ctx.fillStyle=run.freeze>0?'#a6f4ff':'#fff1d7';ctx.fillText(String(Math.ceil(run.remaining)).padStart(2,'0'),190,34);ctx.save();ctx.translate(190,49);if(run.freeze>0){const pulse=1+.09*Math.sin(run.elapsed*7);ctx.scale(pulse,pulse);}ctx.font='bold 10px system-ui';ctx.fillText(run.freeze>0?'ЗАМОРОЗКА':'ДО САЛОНА',0,0);ctx.restore();if(run.freezeBurst<.55){ctx.save();ctx.globalAlpha=1-run.freezeBurst/.55;ctx.strokeStyle='#b7f5ff';for(let j=0;j<10;j++){const a=j*Math.PI/5,r=10+run.freezeBurst*65;ctx.beginPath();ctx.moveTo(190+Math.cos(a)*r,47+Math.sin(a)*r*.5);ctx.lineTo(190+Math.cos(a)*(r+5),47+Math.sin(a)*(r+5)*.5);ctx.stroke();}ctx.restore();}ctx.textAlign='left';ctx.font='bold 12px system-ui';ctx.fillStyle='#fff2dd';ctx.fillText(`${run.score} очков`,15,63);ctx.fillStyle='#49354a';ctx.fillRect(15,70,360,4);ctx.fillStyle='#b9e5d5';ctx.fillRect(15,70,360*clamp(run.score/1000),4);ctx.font='bold 9px system-ui';for(const [n,label] of [[0,'5%'],[550,'10% · 550'],[1000,'15% · 1000']]){const x=15+360*n/1000;ctx.fillStyle='#fff0d9';ctx.fillRect(x-1,68,2,8);ctx.textAlign=n===0?'left':n===1000?'right':'center';ctx.fillText(label,x,88);}ctx.restore();}
function draw(){if(!ready)return;time=run.elapsed;const final=run.mode==='finale'||run.mode==='victory',s=castlePose();let mark=performance.now();city.draw(ctx,390,700,final?82+s.scroll/94:run.progress,{nearEnd:run.progress>=82?s.cx+s.cw*.065:undefined});if(run.progress>=82)ctx.drawImage(castle,s.cx,s.cy,s.cw,s.ch);
GamePerf.section('city',performance.now()-mark);mark=performance.now();
for(const o of run.objects){if(o.type===7&&o.warn>=0){ctx.save();ctx.strokeStyle='#ff914faa';ctx.setLineDash([4,5]);ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(o.x,o.y,BALANCE.bomb.radius,0,7);ctx.stroke();ctx.restore();}object(ctx,o.type,run.elapsed,o.x,o.y,o.size,o.id,o.warn>=0?o.warn:100,o.rotation||0);}
for(const b of run.blasts){const q=b.age/BALANCE.bomb.blastDuration;ctx.save();ctx.translate(b.x,b.y);ctx.globalAlpha=1-q;const glow=ctx.createRadialGradient(0,0,0,0,0,65);glow.addColorStop(0,'#fff8dbaa');glow.addColorStop(.25,'#ffb35c88');glow.addColorStop(1,'#c637ee00');ctx.fillStyle=glow;ctx.fillRect(-65,-65,130,130);for(let j=0;j<30;j++){const a=j*2.399+rand(b.seed)*6,r=(10+rand(j+b.seed)*65)*Math.sin(q*Math.PI/2),x=Math.cos(a)*r,y=Math.sin(a)*r+q*q*25;ctx.save();ctx.translate(x,y);ctx.rotate(a+q*(j%2?5:-5));ctx.fillStyle=['#ffbe67','#fff3d4','#d98eff','#b7faff'][j%4];ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=4;ctx.beginPath();ctx.moveTo(-2,-3);ctx.lineTo(3,0);ctx.lineTo(0,4);ctx.closePath();ctx.fill();ctx.restore();}ctx.restore();}

GamePerf.section('items',performance.now()-mark);mark=performance.now();
ctx.save();if(final&&s.enter>0){ctx.beginPath();ctx.rect(0,0,s.cx+s.cw*.65,700);ctx.clip();}drawWitch();ctx.restore();if(final&&s.enter>0){const l=.65;ctx.drawImage(castle,castle.width*l,castle.height*.58,castle.width*(1-l),castle.height*.42,s.cx+s.cw*l,s.cy+s.ch*.58,s.cw*(1-l),s.ch*.42);}
GamePerf.section('witchAndAura',performance.now()-mark);
for(const e of fxEvents)fx(ctx,e.item,run.elapsed-e.at,e.x,e.y,45);
if(run.shieldFlash<.35){ctx.save();ctx.strokeStyle='#d5ffff';ctx.globalAlpha=1-run.shieldFlash/.35;ctx.beginPath();ctx.ellipse(165,run.y,64+run.shieldFlash*20,43+run.shieldFlash*20,witch.pose.angle,0,7);ctx.stroke();ctx.restore();}
if(el('hitboxes').checked){ctx.save();for(const z of run.pickupZones()){ctx.strokeStyle='#7beaff';ctx.beginPath();ctx.ellipse(z.x,z.y,z.rx,z.ry,0,0,7);ctx.stroke();}ctx.strokeStyle='#8bff89';ctx.beginPath();ctx.ellipse(165,run.y,BALANCE.player.rx,BALANCE.player.ry,0,0,7);ctx.stroke();for(const o of run.objects){ctx.beginPath();ctx.arc(o.x,o.y,o.size*.3,0,7);ctx.stroke();}ctx.restore();}if(!final)hud();}
function updateResults(){el('perfBadge').style.visibility='hidden';const panel=document.querySelector('.result'),discount=run.tier();panel.hidden=false;panel.querySelector('h2').textContent=run.mode==='victory'?'ТЫ ДОЛЕТЕЛА!':'ЕЩЁ ОДИН ПОЛЁТ?';panel.querySelector('.score').textContent=run.score;panel.querySelector('.reward').textContent=discount+'%';panel.querySelector('.tiers').innerHTML=[[0,5],[550,10],[1000,15]].map(([n,d])=>`<li class="${d===discount?'current':run.score>=n?'passed':'locked'}"><b>${d}%</b><span>${d===discount?'ТВОЙ УРОВЕНЬ':run.score>=n?'Получено':'Ещё '+(n-run.score)+' очков'}</span></li>`).join('');panel.querySelector('.motivation').textContent=discount===15?'Максимальный уровень. Красиво летишь.':'Ещё один полёт — и скидка выше.';panel.querySelector('.claimNote').textContent='';el('potionMode').disabled=false;el('seed').disabled=false;applyResultLayout();exportReport(false);}
document.querySelector('.again').onclick=start;document.querySelector('.claim').onclick=()=>RewardClaim.open(run.tier());
function exportReport(copy){const report={version:'playtest-v6',seed:run.seed,experimental:run.experimental,mode:run.mode,score:run.score,discount:run.tier(),lives:run.lives,seconds:+run.elapsed.toFixed(2),freezeSeconds:run.freezeSpent,performance:GamePerf.summary(),...run.stats};el('report').value=JSON.stringify(report,null,2);if(copy){const fallback=()=>{el('report').focus();el('report').select();el('report').setSelectionRange(0,el('report').value.length);let copied=false;try{copied=document.execCommand('copy');}catch{}el('testStatus').textContent=copied?'Отчёт скопирован':'Удержи выделенный отчёт и выбери «Скопировать»';};if(navigator.clipboard?.writeText)navigator.clipboard.writeText(el('report').value).then(()=>el('testStatus').textContent='Отчёт скопирован').catch(fallback);else fallback();}return report;}
el('exportRun').onclick=()=>exportReport(true);new ResizeObserver(()=>{if(!document.querySelector('.result').hidden)applyResultLayout();}).observe(el('frame'));
let previousVisual=null;
function captureVisual(){return {mode:run.mode,values:Object.fromEntries(['elapsed','progress','remaining','finale','y','vy'].map(k=>[k,run[k]])),pose:{...witch.pose},witchTime:witch.time,hat:witch.hatSlip,objects:new Map(run.objects.map(o=>[o.id,{x:o.x,y:o.y,age:o.age,warn:o.warn,rotation:o.rotation}]))};}
function drawInterpolated(alpha){
 if(!previousVisual||previousVisual.mode!==run.mode){draw();return;}
 const saved=captureVisual(),mix=(a,b)=>a+(b-a)*alpha;
 try{for(const k of Object.keys(saved.values))run[k]=mix(previousVisual.values[k],saved.values[k]);
 for(const k of Object.keys(saved.pose))witch.pose[k]=mix(previousVisual.pose[k],saved.pose[k]);
 witch.time=mix(previousVisual.witchTime,saved.witchTime);witch.hatSlip=mix(previousVisual.hat,saved.hat);
 for(const o of run.objects){const p=previousVisual.objects.get(o.id),n=saved.objects.get(o.id);if(p)for(const k of ['x','y','age','warn','rotation'])if(Number.isFinite(p[k])&&Number.isFinite(n[k]))o[k]=mix(p[k],n[k]);}
 draw();
 }finally{Object.assign(run,saved.values);witch.pose=saved.pose;witch.time=saved.witchTime;witch.hatSlip=saved.hat;for(const o of run.objects)Object.assign(o,saved.objects.get(o.id));}
}
function step(dt){previousVisual=captureVisual();run.update(dt,pressed);time=run.elapsed;for(const e of run.events.splice(0)){if(e.type==='pickup'){fxEvents.push({...e,at:run.elapsed});tone(e.item===2?900:650);}if(e.type==='hit')tone(140);if(e.type==='shieldHit')tone(400);if(e.type==='finale'){clearInput();fxEvents=[];witch.trail=[];}if(['victory','gameover'].includes(e.type)){clearInput();fxEvents=[];updateResults();}}fxEvents=fxEvents.filter(e=>run.elapsed-e.at<1);const final=run.mode==='finale'||run.mode==='victory',s=castlePose();witch.update(dt,{x:final?s.x:165,y:final?s.y:run.y,height:final?s.height:70,vy:final?0:run.vy,pressed:!final&&pressed,emit:run.mode==='playing'||run.mode==='finale'});}
function loop(now){if(ready&&started&&run.progress>=10&&!backgroundReady&&!assetWaiting){assetWaiting=true;clearInput();accumulator=0;el('assetWait').hidden=false;}
const frameMs=now-frameLast,dt=Math.min(.1,Math.max(0,frameMs/1000));frameLast=now;if(ready&&started&&!paused&&!assetWaiting&&['playing','finale'].includes(run.mode)){accumulator+=dt;while(accumulator>=1/120){step(1/120);accumulator-=1/120;}const drawStart=performance.now();drawInterpolated(accumulator*120);GamePerf.frame(frameMs,performance.now()-drawStart,now,{seconds:+run.progress.toFixed(1),objects:run.objects.length,shield:run.shield>0,train:run.progress>=41&&run.progress<50});}requestAnimationFrame(loop);}
function startBackground(){if(backgroundBusy)return backgroundLoaded;backgroundBusy=true;el('retryLate').hidden=true;el('lateMessage').textContent='Подгружаем следующий район. Полёт на паузе.';
 backgroundLoaded=Promise.all([city.loadLater(),loadImage('../finale-v1/castle-gothic.png').then(im=>castle=im)]).then(()=>{backgroundReady=true;GameAssets.release();if(assetWaiting){assetWaiting=false;el('assetWait').hidden=true;setPaused(true);}return true;}).catch(e=>{el('lateMessage').textContent='Не удалось загрузить район. Проверь Wi‑Fi и повтори — результат сохранён.';el('retryLate').hidden=false;return false;}).finally(()=>backgroundBusy=false);return backgroundLoaded;
}
el('retryLate').onclick=()=>startBackground();
const loaded=Promise.all([itemsLoaded,city.loaded,witch.loaded,loadImage('../hud-v1/aura.png'),loadImage('../finale-v1/result-frame-alpha.png')]).then(a=>{auraImage=a[3];prepareAura();auraImage=null;city.prepare();ready=true;GameAssets.finish();witch.update(0,{x:165,y:295,height:70,emit:false});draw();el('start').disabled=false;el('start').textContent='ПОЛЕТЕЛИ';el('loadStatus').textContent='';frameLast=performance.now();requestAnimationFrame(loop);startBackground();}).catch(e=>{GameAssets.fail();el('loadStatus').textContent=e.message+' · обновите страницу';throw e;});
window.playtest={run,config:BALANCE,start,pause:setPaused,step,draw,drawInterpolated,background:()=>backgroundLoaded,report:()=>exportReport(false)};

