window.GamePerf=(()=>{
 const frames=[],renders=[],sections={},stalls=[],badge=document.getElementById('perfBadge');let count=0,total=0,slow=0,nextUpdate=0,maxFrame=0,longTasks=0,longTaskMax=0;
 const bins={under18:0,under25:0,under34:0,under50:0,over50:0};
 const average=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
 function sample(a,n){a.push(n);if(a.length>600)a.shift();}
 function summary(){const sorted=[...frames].sort((a,b)=>a-b),mean=average(frames),pct=q=>sorted.length?+sorted[Math.min(sorted.length-1,Math.floor(sorted.length*q))].toFixed(1):null;return {averageFps:total?+(count*1000/total).toFixed(1):null,recentFps:frames.length?+(1000/average(frames.slice(-60))).toFixed(1):null,frameP95Ms:pct(.95),frameP99Ms:pct(.99),maxFrameMs:+maxFrame.toFixed(1),frameJitterMs:+Math.sqrt(average(frames.map(n=>(n-mean)**2))).toFixed(2),renderCpuMs:+average(renders).toFixed(2),slowFramesPercent:count?+(slow/count*100).toFixed(1):0,frames:count,frameHistogram:{...bins},worstFrames:[...stalls],longTasks,longTaskMaxMs:+longTaskMax.toFixed(1),sectionsCpuMs:Object.fromEntries(Object.entries(sections).map(([k,a])=>[k,+average(a).toFixed(2)]))};}
 try{if(PerformanceObserver.supportedEntryTypes?.includes('longtask'))new PerformanceObserver(list=>{for(const e of list.getEntries()){longTasks++;longTaskMax=Math.max(longTaskMax,e.duration);}}).observe({type:'longtask'});}catch{}
 return {reset(){frames.length=renders.length=stalls.length=0;for(const a of Object.values(sections))a.length=0;for(const k of Object.keys(bins))bins[k]=0;count=total=slow=nextUpdate=maxFrame=longTasks=longTaskMax=0;badge.textContent='FPS · замер…';},frame(dt,renderMs,now,context={}){if(dt>0){sample(frames,dt);sample(renders,renderMs);count++;total+=dt;maxFrame=Math.max(maxFrame,dt);bins[dt<18?'under18':dt<25?'under25':dt<34?'under34':dt<50?'under50':'over50']++;if(dt>25){slow++;stalls.push({frameMs:+dt.toFixed(1),renderMs:+renderMs.toFixed(1),...context});stalls.sort((a,b)=>b.frameMs-a.frameMs);stalls.length=Math.min(12,stalls.length);}}if(now>=nextUpdate){nextUpdate=now+500;const s=summary();badge.textContent=`${s.recentFps??'—'} FPS · P95 ${s.frameP95Ms??'—'} мс`;badge.hidden=!document.getElementById('showFps').checked;}},section(name,ms){sample(sections[name]??=[],ms);},summary};
})();
